name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:       

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: "hhatinen@gmail.com"      
      - name: Login to Heroku
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
      - name: Deploy SECRET_KEY
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku config:set SECRET_KEY=${{ secrets.FLASK_SECRET_KEY }}
      - name: Set FLASK_APP
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku config:set FLASK_APP=app
      - name: Migrate DB
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku psql < schema.sql
